name: CI Pipeline

on: 
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Run PowerShell Script
        run: pwsh ./create-storage-account.ps1
